title: "OD Videos"
description: "Profesionální videa a fotografie z dronu. Záběry z dronu, letecké záběry, letecké fotografie, letecké video, letecká fotografie, letecké snímky, letecké záběry, letecké fotografie, letecké video, letecká fotografie, letecké snímky, letecké záběry, letecké fotografie, letecké video, letecká fotografie, letecké snímky, letecké záběry, letecké fotografie, letecké video, letecká fotografie, letecké snímky"
logo: "/assets/images/logo/logo-color.png"

url: "https://odvideos.cz"
baseurl: ""

lang: cs-CZ

author:
  name: "Ondřej Demuth"
  email: "od.videomaker@gmail.com"


social:
  name: "OD Videos"
  links:
    - https://www.instagram.com/od_videos/

permalink: pretty


# Exclude raw development files from the production build
exclude:
  - .devcontainer/
  - Gemfile
  - Gemfile.lock
  - old/
  - .git/
  - README.md
  - TODO.md

# Required plugins for SEO and sitemap generation
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap